name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: non-prod
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: ./bun install
      - name: Run Biome Linter
        run: ./bun run lint
      - name: Run Type Check
        run: ./bun run typecheck
      - name: Run Tests
        run: ./bun test
